services:
  postgres-linkedin-data:
    image: postgres:16-alpine
    ports:
      - 1201:5432
    volumes:
      - uservice_linkedin_data_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
volumes:
  uservice_linkedin_data_postgres:
