// Code generated by mockery v2.43.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-linkedin-data/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockGetUserService is an autogenerated mock type for the GetUserService type
type MockGetUserService struct {
	mock.Mock
}

type MockGetUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetUserService) EXPECT() *MockGetUserService_Expecter {
	return &MockGetUserService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, publicIdentifier
func (_m *MockGetUserService) Exec(ctx context.Context, publicIdentifier string) (*models.User, error) {
	ret := _m.Called(ctx, publicIdentifier)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, publicIdentifier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, publicIdentifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, publicIdentifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetUserService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGetUserService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - publicIdentifier string
func (_e *MockGetUserService_Expecter) Exec(ctx interface{}, publicIdentifier interface{}) *MockGetUserService_Exec_Call {
	return &MockGetUserService_Exec_Call{Call: _e.mock.On("Exec", ctx, publicIdentifier)}
}

func (_c *MockGetUserService_Exec_Call) Run(run func(ctx context.Context, publicIdentifier string)) *MockGetUserService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGetUserService_Exec_Call) Return(_a0 *models.User, _a1 error) *MockGetUserService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetUserService_Exec_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockGetUserService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetUserService creates a new instance of MockGetUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetUserService {
	mock := &MockGetUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
