// Code generated by mockery v2.43.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-linkedin-data/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockGetCompanyService is an autogenerated mock type for the GetCompanyService type
type MockGetCompanyService struct {
	mock.Mock
}

type MockGetCompanyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetCompanyService) EXPECT() *MockGetCompanyService_Expecter {
	return &MockGetCompanyService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, publicIdentifier
func (_m *MockGetCompanyService) Exec(ctx context.Context, publicIdentifier string) (*models.Company, error) {
	ret := _m.Called(ctx, publicIdentifier)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *models.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Company, error)); ok {
		return rf(ctx, publicIdentifier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Company); ok {
		r0 = rf(ctx, publicIdentifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, publicIdentifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetCompanyService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGetCompanyService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - publicIdentifier string
func (_e *MockGetCompanyService_Expecter) Exec(ctx interface{}, publicIdentifier interface{}) *MockGetCompanyService_Exec_Call {
	return &MockGetCompanyService_Exec_Call{Call: _e.mock.On("Exec", ctx, publicIdentifier)}
}

func (_c *MockGetCompanyService_Exec_Call) Run(run func(ctx context.Context, publicIdentifier string)) *MockGetCompanyService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGetCompanyService_Exec_Call) Return(_a0 *models.Company, _a1 error) *MockGetCompanyService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetCompanyService_Exec_Call) RunAndReturn(run func(context.Context, string) (*models.Company, error)) *MockGetCompanyService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetCompanyService creates a new instance of MockGetCompanyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetCompanyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetCompanyService {
	mock := &MockGetCompanyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
