// Code generated by mockery v2.43.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-linkedin-data/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockUpsertUserService is an autogenerated mock type for the UpsertUserService type
type MockUpsertUserService struct {
	mock.Mock
}

type MockUpsertUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpsertUserService) EXPECT() *MockUpsertUserService_Expecter {
	return &MockUpsertUserService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, publicIdentifier, data
func (_m *MockUpsertUserService) Exec(ctx context.Context, publicIdentifier string, data *models.UpsertUser) (*models.User, error) {
	ret := _m.Called(ctx, publicIdentifier, data)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.UpsertUser) (*models.User, error)); ok {
		return rf(ctx, publicIdentifier, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.UpsertUser) *models.User); ok {
		r0 = rf(ctx, publicIdentifier, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *models.UpsertUser) error); ok {
		r1 = rf(ctx, publicIdentifier, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpsertUserService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockUpsertUserService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - publicIdentifier string
//   - data *models.UpsertUser
func (_e *MockUpsertUserService_Expecter) Exec(ctx interface{}, publicIdentifier interface{}, data interface{}) *MockUpsertUserService_Exec_Call {
	return &MockUpsertUserService_Exec_Call{Call: _e.mock.On("Exec", ctx, publicIdentifier, data)}
}

func (_c *MockUpsertUserService_Exec_Call) Run(run func(ctx context.Context, publicIdentifier string, data *models.UpsertUser)) *MockUpsertUserService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*models.UpsertUser))
	})
	return _c
}

func (_c *MockUpsertUserService_Exec_Call) Return(_a0 *models.User, _a1 error) *MockUpsertUserService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpsertUserService_Exec_Call) RunAndReturn(run func(context.Context, string, *models.UpsertUser) (*models.User, error)) *MockUpsertUserService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpsertUserService creates a new instance of MockUpsertUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpsertUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpsertUserService {
	mock := &MockUpsertUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
