// Code generated by mockery v2.43.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-linkedin-data/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockListUsersService is an autogenerated mock type for the ListUsersService type
type MockListUsersService struct {
	mock.Mock
}

type MockListUsersService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListUsersService) EXPECT() *MockListUsersService_Expecter {
	return &MockListUsersService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, publicIdentifiers
func (_m *MockListUsersService) Exec(ctx context.Context, publicIdentifiers []string) ([]*models.User, error) {
	ret := _m.Called(ctx, publicIdentifiers)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*models.User, error)); ok {
		return rf(ctx, publicIdentifiers)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*models.User); ok {
		r0 = rf(ctx, publicIdentifiers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, publicIdentifiers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListUsersService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockListUsersService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - publicIdentifiers []string
func (_e *MockListUsersService_Expecter) Exec(ctx interface{}, publicIdentifiers interface{}) *MockListUsersService_Exec_Call {
	return &MockListUsersService_Exec_Call{Call: _e.mock.On("Exec", ctx, publicIdentifiers)}
}

func (_c *MockListUsersService_Exec_Call) Run(run func(ctx context.Context, publicIdentifiers []string)) *MockListUsersService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockListUsersService_Exec_Call) Return(_a0 []*models.User, _a1 error) *MockListUsersService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListUsersService_Exec_Call) RunAndReturn(run func(context.Context, []string) ([]*models.User, error)) *MockListUsersService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListUsersService creates a new instance of MockListUsersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListUsersService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListUsersService {
	mock := &MockListUsersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
