// Code generated by mockery v2.43.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockGetCompanyLastUpdateService is an autogenerated mock type for the GetCompanyLastUpdateService type
type MockGetCompanyLastUpdateService struct {
	mock.Mock
}

type MockGetCompanyLastUpdateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetCompanyLastUpdateService) EXPECT() *MockGetCompanyLastUpdateService_Expecter {
	return &MockGetCompanyLastUpdateService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, publicIdentifier
func (_m *MockGetCompanyLastUpdateService) Exec(ctx context.Context, publicIdentifier string) (*time.Time, error) {
	ret := _m.Called(ctx, publicIdentifier)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*time.Time, error)); ok {
		return rf(ctx, publicIdentifier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *time.Time); ok {
		r0 = rf(ctx, publicIdentifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, publicIdentifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetCompanyLastUpdateService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGetCompanyLastUpdateService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - publicIdentifier string
func (_e *MockGetCompanyLastUpdateService_Expecter) Exec(ctx interface{}, publicIdentifier interface{}) *MockGetCompanyLastUpdateService_Exec_Call {
	return &MockGetCompanyLastUpdateService_Exec_Call{Call: _e.mock.On("Exec", ctx, publicIdentifier)}
}

func (_c *MockGetCompanyLastUpdateService_Exec_Call) Run(run func(ctx context.Context, publicIdentifier string)) *MockGetCompanyLastUpdateService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGetCompanyLastUpdateService_Exec_Call) Return(_a0 *time.Time, _a1 error) *MockGetCompanyLastUpdateService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetCompanyLastUpdateService_Exec_Call) RunAndReturn(run func(context.Context, string) (*time.Time, error)) *MockGetCompanyLastUpdateService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetCompanyLastUpdateService creates a new instance of MockGetCompanyLastUpdateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetCompanyLastUpdateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetCompanyLastUpdateService {
	mock := &MockGetCompanyLastUpdateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
