// Code generated by mockery v2.43.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-linkedin-data/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockUpsertCompanyService is an autogenerated mock type for the UpsertCompanyService type
type MockUpsertCompanyService struct {
	mock.Mock
}

type MockUpsertCompanyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpsertCompanyService) EXPECT() *MockUpsertCompanyService_Expecter {
	return &MockUpsertCompanyService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, publicIdentifier, data
func (_m *MockUpsertCompanyService) Exec(ctx context.Context, publicIdentifier string, data *models.UpsertCompany) (*models.Company, error) {
	ret := _m.Called(ctx, publicIdentifier, data)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *models.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.UpsertCompany) (*models.Company, error)); ok {
		return rf(ctx, publicIdentifier, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.UpsertCompany) *models.Company); ok {
		r0 = rf(ctx, publicIdentifier, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *models.UpsertCompany) error); ok {
		r1 = rf(ctx, publicIdentifier, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpsertCompanyService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockUpsertCompanyService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - publicIdentifier string
//   - data *models.UpsertCompany
func (_e *MockUpsertCompanyService_Expecter) Exec(ctx interface{}, publicIdentifier interface{}, data interface{}) *MockUpsertCompanyService_Exec_Call {
	return &MockUpsertCompanyService_Exec_Call{Call: _e.mock.On("Exec", ctx, publicIdentifier, data)}
}

func (_c *MockUpsertCompanyService_Exec_Call) Run(run func(ctx context.Context, publicIdentifier string, data *models.UpsertCompany)) *MockUpsertCompanyService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*models.UpsertCompany))
	})
	return _c
}

func (_c *MockUpsertCompanyService_Exec_Call) Return(_a0 *models.Company, _a1 error) *MockUpsertCompanyService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpsertCompanyService_Exec_Call) RunAndReturn(run func(context.Context, string, *models.UpsertCompany) (*models.Company, error)) *MockUpsertCompanyService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpsertCompanyService creates a new instance of MockUpsertCompanyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpsertCompanyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpsertCompanyService {
	mock := &MockUpsertCompanyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
