auth-domain: inrich-dev.firebaseapp.com
project-id: inrich-dev
storage-bucket: inrich-dev.appspot.com
messaging-sender-id: 434550576966
app-id: 1:434550576966:web:68c417aff82fdfb5c2f747
api-key: AIzaSyDEk7E482bL_XUrDEP71PzqHPpF7xLwSow

buckets:
  profile-pictures: inrich-dev-profile-pictures
  company-logos: inrich-dev-company-logos
