auth-domain: inrich-f9a0a.firebaseapp.com
project-id: inrich-f9a0a
storage-bucket: inrich-f9a0a.appspot.coms
messaging-sender-id: 1073342656628
app-id: 1:1073342656628:web:fd94e7d1716b1e848b2121
measurement-id: G-SP95889111

buckets:
  profile-pictures: inrich-prod-profile-pictures
  company-logos: inrich-prod-company-logos
