// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	dao "github.com/in-rich/uservice-linkedin-data/pkg/dao"
	entities "github.com/in-rich/uservice-linkedin-data/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockUpdateUserRepository is an autogenerated mock type for the UpdateUserRepository type
type MockUpdateUserRepository struct {
	mock.Mock
}

type MockUpdateUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateUserRepository) EXPECT() *MockUpdateUserRepository_Expecter {
	return &MockUpdateUserRepository_Expecter{mock: &_m.Mock}
}

// UpdateUser provides a mock function with given fields: ctx, publicIdentifier, data
func (_m *MockUpdateUserRepository) UpdateUser(ctx context.Context, publicIdentifier string, data *dao.UpdateUserData) (*entities.User, error) {
	ret := _m.Called(ctx, publicIdentifier, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dao.UpdateUserData) (*entities.User, error)); ok {
		return rf(ctx, publicIdentifier, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dao.UpdateUserData) *entities.User); ok {
		r0 = rf(ctx, publicIdentifier, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dao.UpdateUserData) error); ok {
		r1 = rf(ctx, publicIdentifier, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateUserRepository_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUpdateUserRepository_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - publicIdentifier string
//   - data *dao.UpdateUserData
func (_e *MockUpdateUserRepository_Expecter) UpdateUser(ctx interface{}, publicIdentifier interface{}, data interface{}) *MockUpdateUserRepository_UpdateUser_Call {
	return &MockUpdateUserRepository_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, publicIdentifier, data)}
}

func (_c *MockUpdateUserRepository_UpdateUser_Call) Run(run func(ctx context.Context, publicIdentifier string, data *dao.UpdateUserData)) *MockUpdateUserRepository_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*dao.UpdateUserData))
	})
	return _c
}

func (_c *MockUpdateUserRepository_UpdateUser_Call) Return(_a0 *entities.User, _a1 error) *MockUpdateUserRepository_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateUserRepository_UpdateUser_Call) RunAndReturn(run func(context.Context, string, *dao.UpdateUserData) (*entities.User, error)) *MockUpdateUserRepository_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateUserRepository creates a new instance of MockUpdateUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateUserRepository {
	mock := &MockUpdateUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
