// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockGetCompanyLastUpdateRepository is an autogenerated mock type for the GetCompanyLastUpdateRepository type
type MockGetCompanyLastUpdateRepository struct {
	mock.Mock
}

type MockGetCompanyLastUpdateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetCompanyLastUpdateRepository) EXPECT() *MockGetCompanyLastUpdateRepository_Expecter {
	return &MockGetCompanyLastUpdateRepository_Expecter{mock: &_m.Mock}
}

// GetCompanyLastUpdate provides a mock function with given fields: ctx, publicIdentifier
func (_m *MockGetCompanyLastUpdateRepository) GetCompanyLastUpdate(ctx context.Context, publicIdentifier string) (*time.Time, error) {
	ret := _m.Called(ctx, publicIdentifier)

	if len(ret) == 0 {
		panic("no return value specified for GetCompanyLastUpdate")
	}

	var r0 *time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*time.Time, error)); ok {
		return rf(ctx, publicIdentifier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *time.Time); ok {
		r0 = rf(ctx, publicIdentifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, publicIdentifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetCompanyLastUpdateRepository_GetCompanyLastUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompanyLastUpdate'
type MockGetCompanyLastUpdateRepository_GetCompanyLastUpdate_Call struct {
	*mock.Call
}

// GetCompanyLastUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - publicIdentifier string
func (_e *MockGetCompanyLastUpdateRepository_Expecter) GetCompanyLastUpdate(ctx interface{}, publicIdentifier interface{}) *MockGetCompanyLastUpdateRepository_GetCompanyLastUpdate_Call {
	return &MockGetCompanyLastUpdateRepository_GetCompanyLastUpdate_Call{Call: _e.mock.On("GetCompanyLastUpdate", ctx, publicIdentifier)}
}

func (_c *MockGetCompanyLastUpdateRepository_GetCompanyLastUpdate_Call) Run(run func(ctx context.Context, publicIdentifier string)) *MockGetCompanyLastUpdateRepository_GetCompanyLastUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGetCompanyLastUpdateRepository_GetCompanyLastUpdate_Call) Return(_a0 *time.Time, _a1 error) *MockGetCompanyLastUpdateRepository_GetCompanyLastUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetCompanyLastUpdateRepository_GetCompanyLastUpdate_Call) RunAndReturn(run func(context.Context, string) (*time.Time, error)) *MockGetCompanyLastUpdateRepository_GetCompanyLastUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetCompanyLastUpdateRepository creates a new instance of MockGetCompanyLastUpdateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetCompanyLastUpdateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetCompanyLastUpdateRepository {
	mock := &MockGetCompanyLastUpdateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
