// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	entities "github.com/in-rich/uservice-linkedin-data/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockGetCompanyRepository is an autogenerated mock type for the GetCompanyRepository type
type MockGetCompanyRepository struct {
	mock.Mock
}

type MockGetCompanyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetCompanyRepository) EXPECT() *MockGetCompanyRepository_Expecter {
	return &MockGetCompanyRepository_Expecter{mock: &_m.Mock}
}

// GetCompany provides a mock function with given fields: ctx, publicIdentifier
func (_m *MockGetCompanyRepository) GetCompany(ctx context.Context, publicIdentifier string) (*entities.Company, error) {
	ret := _m.Called(ctx, publicIdentifier)

	if len(ret) == 0 {
		panic("no return value specified for GetCompany")
	}

	var r0 *entities.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Company, error)); ok {
		return rf(ctx, publicIdentifier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Company); ok {
		r0 = rf(ctx, publicIdentifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, publicIdentifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetCompanyRepository_GetCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompany'
type MockGetCompanyRepository_GetCompany_Call struct {
	*mock.Call
}

// GetCompany is a helper method to define mock.On call
//   - ctx context.Context
//   - publicIdentifier string
func (_e *MockGetCompanyRepository_Expecter) GetCompany(ctx interface{}, publicIdentifier interface{}) *MockGetCompanyRepository_GetCompany_Call {
	return &MockGetCompanyRepository_GetCompany_Call{Call: _e.mock.On("GetCompany", ctx, publicIdentifier)}
}

func (_c *MockGetCompanyRepository_GetCompany_Call) Run(run func(ctx context.Context, publicIdentifier string)) *MockGetCompanyRepository_GetCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGetCompanyRepository_GetCompany_Call) Return(_a0 *entities.Company, _a1 error) *MockGetCompanyRepository_GetCompany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetCompanyRepository_GetCompany_Call) RunAndReturn(run func(context.Context, string) (*entities.Company, error)) *MockGetCompanyRepository_GetCompany_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetCompanyRepository creates a new instance of MockGetCompanyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetCompanyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetCompanyRepository {
	mock := &MockGetCompanyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
