// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	entities "github.com/in-rich/uservice-linkedin-data/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockListCompaniesRepository is an autogenerated mock type for the ListCompaniesRepository type
type MockListCompaniesRepository struct {
	mock.Mock
}

type MockListCompaniesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListCompaniesRepository) EXPECT() *MockListCompaniesRepository_Expecter {
	return &MockListCompaniesRepository_Expecter{mock: &_m.Mock}
}

// ListCompanies provides a mock function with given fields: ctx, publicIdentifiers
func (_m *MockListCompaniesRepository) ListCompanies(ctx context.Context, publicIdentifiers []string) ([]*entities.Company, error) {
	ret := _m.Called(ctx, publicIdentifiers)

	if len(ret) == 0 {
		panic("no return value specified for ListCompanies")
	}

	var r0 []*entities.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*entities.Company, error)); ok {
		return rf(ctx, publicIdentifiers)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*entities.Company); ok {
		r0 = rf(ctx, publicIdentifiers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, publicIdentifiers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListCompaniesRepository_ListCompanies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCompanies'
type MockListCompaniesRepository_ListCompanies_Call struct {
	*mock.Call
}

// ListCompanies is a helper method to define mock.On call
//   - ctx context.Context
//   - publicIdentifiers []string
func (_e *MockListCompaniesRepository_Expecter) ListCompanies(ctx interface{}, publicIdentifiers interface{}) *MockListCompaniesRepository_ListCompanies_Call {
	return &MockListCompaniesRepository_ListCompanies_Call{Call: _e.mock.On("ListCompanies", ctx, publicIdentifiers)}
}

func (_c *MockListCompaniesRepository_ListCompanies_Call) Run(run func(ctx context.Context, publicIdentifiers []string)) *MockListCompaniesRepository_ListCompanies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockListCompaniesRepository_ListCompanies_Call) Return(_a0 []*entities.Company, _a1 error) *MockListCompaniesRepository_ListCompanies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListCompaniesRepository_ListCompanies_Call) RunAndReturn(run func(context.Context, []string) ([]*entities.Company, error)) *MockListCompaniesRepository_ListCompanies_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListCompaniesRepository creates a new instance of MockListCompaniesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListCompaniesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListCompaniesRepository {
	mock := &MockListCompaniesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
