// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	dao "github.com/in-rich/uservice-linkedin-data/pkg/dao"
	entities "github.com/in-rich/uservice-linkedin-data/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockCreateUserRepository is an autogenerated mock type for the CreateUserRepository type
type MockCreateUserRepository struct {
	mock.Mock
}

type MockCreateUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateUserRepository) EXPECT() *MockCreateUserRepository_Expecter {
	return &MockCreateUserRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, publicIdentifier, data
func (_m *MockCreateUserRepository) CreateUser(ctx context.Context, publicIdentifier string, data *dao.CreateUserData) (*entities.User, error) {
	ret := _m.Called(ctx, publicIdentifier, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dao.CreateUserData) (*entities.User, error)); ok {
		return rf(ctx, publicIdentifier, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dao.CreateUserData) *entities.User); ok {
		r0 = rf(ctx, publicIdentifier, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dao.CreateUserData) error); ok {
		r1 = rf(ctx, publicIdentifier, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateUserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockCreateUserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - publicIdentifier string
//   - data *dao.CreateUserData
func (_e *MockCreateUserRepository_Expecter) CreateUser(ctx interface{}, publicIdentifier interface{}, data interface{}) *MockCreateUserRepository_CreateUser_Call {
	return &MockCreateUserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, publicIdentifier, data)}
}

func (_c *MockCreateUserRepository_CreateUser_Call) Run(run func(ctx context.Context, publicIdentifier string, data *dao.CreateUserData)) *MockCreateUserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*dao.CreateUserData))
	})
	return _c
}

func (_c *MockCreateUserRepository_CreateUser_Call) Return(_a0 *entities.User, _a1 error) *MockCreateUserRepository_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateUserRepository_CreateUser_Call) RunAndReturn(run func(context.Context, string, *dao.CreateUserData) (*entities.User, error)) *MockCreateUserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateUserRepository creates a new instance of MockCreateUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateUserRepository {
	mock := &MockCreateUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
