// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	entities "github.com/in-rich/uservice-linkedin-data/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockGetUserRepository is an autogenerated mock type for the GetUserRepository type
type MockGetUserRepository struct {
	mock.Mock
}

type MockGetUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetUserRepository) EXPECT() *MockGetUserRepository_Expecter {
	return &MockGetUserRepository_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function with given fields: ctx, publicIdentifier
func (_m *MockGetUserRepository) GetUser(ctx context.Context, publicIdentifier string) (*entities.User, error) {
	ret := _m.Called(ctx, publicIdentifier)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.User, error)); ok {
		return rf(ctx, publicIdentifier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.User); ok {
		r0 = rf(ctx, publicIdentifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, publicIdentifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetUserRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockGetUserRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - publicIdentifier string
func (_e *MockGetUserRepository_Expecter) GetUser(ctx interface{}, publicIdentifier interface{}) *MockGetUserRepository_GetUser_Call {
	return &MockGetUserRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, publicIdentifier)}
}

func (_c *MockGetUserRepository_GetUser_Call) Run(run func(ctx context.Context, publicIdentifier string)) *MockGetUserRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGetUserRepository_GetUser_Call) Return(_a0 *entities.User, _a1 error) *MockGetUserRepository_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetUserRepository_GetUser_Call) RunAndReturn(run func(context.Context, string) (*entities.User, error)) *MockGetUserRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetUserRepository creates a new instance of MockGetUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetUserRepository {
	mock := &MockGetUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
