// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUpsertProfilePictureRepository is an autogenerated mock type for the UpsertProfilePictureRepository type
type MockUpsertProfilePictureRepository struct {
	mock.Mock
}

type MockUpsertProfilePictureRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpsertProfilePictureRepository) EXPECT() *MockUpsertProfilePictureRepository_Expecter {
	return &MockUpsertProfilePictureRepository_Expecter{mock: &_m.Mock}
}

// UpsertProfilePicture provides a mock function with given fields: ctx, publicIdentifier, base64
func (_m *MockUpsertProfilePictureRepository) UpsertProfilePicture(ctx context.Context, publicIdentifier string, base64 string) (string, error) {
	ret := _m.Called(ctx, publicIdentifier, base64)

	if len(ret) == 0 {
		panic("no return value specified for UpsertProfilePicture")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, publicIdentifier, base64)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, publicIdentifier, base64)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, publicIdentifier, base64)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpsertProfilePictureRepository_UpsertProfilePicture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertProfilePicture'
type MockUpsertProfilePictureRepository_UpsertProfilePicture_Call struct {
	*mock.Call
}

// UpsertProfilePicture is a helper method to define mock.On call
//   - ctx context.Context
//   - publicIdentifier string
//   - base64 string
func (_e *MockUpsertProfilePictureRepository_Expecter) UpsertProfilePicture(ctx interface{}, publicIdentifier interface{}, base64 interface{}) *MockUpsertProfilePictureRepository_UpsertProfilePicture_Call {
	return &MockUpsertProfilePictureRepository_UpsertProfilePicture_Call{Call: _e.mock.On("UpsertProfilePicture", ctx, publicIdentifier, base64)}
}

func (_c *MockUpsertProfilePictureRepository_UpsertProfilePicture_Call) Run(run func(ctx context.Context, publicIdentifier string, base64 string)) *MockUpsertProfilePictureRepository_UpsertProfilePicture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUpsertProfilePictureRepository_UpsertProfilePicture_Call) Return(_a0 string, _a1 error) *MockUpsertProfilePictureRepository_UpsertProfilePicture_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpsertProfilePictureRepository_UpsertProfilePicture_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockUpsertProfilePictureRepository_UpsertProfilePicture_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpsertProfilePictureRepository creates a new instance of MockUpsertProfilePictureRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpsertProfilePictureRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpsertProfilePictureRepository {
	mock := &MockUpsertProfilePictureRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
